# Sidebar navigation

- label: 'Introdução'
  link: '/'
- label: 'Teste'
  link: '/getting-started'
- label: Procedimentos & BT
  items:
    - label: 'Preventiva Diária - Semanal'
      link: '/procedures/rsm-cirius-ss'
- label: Bizural
  items:
    - label: 'CBP'
      link: '/bizural/cbp'
    - label: 'IBIS'
      link: '/bizural/ibis'
    - label: 'RCMS'
      link: '/bizural/rcms'
- label: Setup Instrumentação
  items:
    - label: FieldFox
      link: /setup/field-fox
    - label: Power Meter
      link: /setup/power-meter
- label: Teoria
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
